# Generated by Django 6.0.6 on 2026-07-01 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('crop', models.CharField(max_length=100)),
                ('disease', models.CharField(max_length=150)),
                ('raw_label', models.CharField(max_length=150)),
                ('confidence', models.FloatField(help_text='Model confidence score, 0-1')),
                ('is_healthy', models.BooleanField(default=False)),
                ('remedy', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
